export { scanLocalVault } from '../../cmd/local/scanLocalVault'
export { scanTarball as parseTarballFromBuffer } from './tarball'
export { verifyReferences } from './verify'
export { timed } from './timed'
export { createSnapshot, diffSnapshot } from './snapshot'
export { octokit, getTarballBuffer } from './octokit'
export { syncNotesToDatabase, saveSnapshotToDatabase } from './sync'
export { extractMetadata } from './metadata'

export type { Note, NoteMeta, FileMeta, Snapshot, SnapshotDiff } from './types'
